name: Publish

on:
  release:
    types: [prereleased, released]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Restore and Build
        uses: ./.github/actions/build

      - name: Run Tests
        run: dotnet run -c Release --no-build --project ./tests/MonoDetour.UnitTests/

      - name: Pack
        run: dotnet pack -c Release --no-build

      - name: Publish NuGet
        run: dotnet nuget push ./artifacts/package/release/*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

      - name: Publish Thunderstore
        env:
          TCLI_AUTH_TOKEN: ${{ secrets.THUNDERSTORE_API_TOKEN }}
        run: dotnet build ./packaging/Thunderstore/ -target:PublishThunderstore
