name: Run Tests

on:
  push:
    branches: [ main ]
  # Trigger the workflow on any pull request
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Restore and Build
        uses: ./.github/actions/build

      - name: Run Tests
        run: dotnet run -c Release --no-build --project ./tests/MonoDetour.UnitTests/
