name: Validate Build and Formatting

on:
  push:
    branches: [ main ]
  # Trigger the workflow on any pull request
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/build
        with:
          additional-build-args: -WarnAsError

      - name: Check Formatting
        run: dotnet csharpier check .
