name: Validate Formatting

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  check_formatting:
    runs-on: ubuntu-latest
    name: Check Formatting
    steps:
      - uses: actions/checkout@v4
      - run: |
          dotnet tool restore
          dotnet csharpier check .
